[program:clickhouse]
command=/usr/local/bin/clickhouse-entrypoint.sh
autostart=true
autorestart=true
startsecs=10
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=CLICKHOUSE_SKIP_USER_SETUP="1",CLICKHOUSE_RUN_AS_ROOT="1",CLICKHOUSE_DO_NOT_CHOWN="1",CLICKHOUSE_CONFIG="/etc/clickhouse-server/config.xml"
