[program:otel-collector]
command=/app/code/scripts/run-otel-collector.sh
autostart=true
autorestart=true
startsecs=10
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=OTEL_RESOURCE_ATTRIBUTES="host.name=signoz-host,os.type=linux",LOW_CARDINAL_EXCEPTION_GROUPING="false",SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN="tcp://127.0.0.1:9000",SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER="cluster",SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION="true",SIGNOZ_OTEL_COLLECTOR_TIMEOUT="10m"
