[program:signoz]
command=/app/code/scripts/run-signoz.sh
autostart=true
autorestart=true
startsecs=15
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=HOME="/opt/signoz",SIGNOZ_ALERTMANAGER_PROVIDER="signoz",SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN="tcp://127.0.0.1:9000"
